name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # ejecuta tus pruebas

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to EC2 Instance
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.USER_NAME }}
          APP_DIR: /home/ubuntu/backend/parcial1-backend
          APP_FILE: app.py
          ENVIRONMENT: production
      
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} << 'EOF'
              # Acceder al directorio del proyecto
              cd /home/ubuntu/backend/parcial1-backend && ls &&

              # Activar el entorno virtual
              source env/bin/activate &&

              # Actualizar el código desde la rama master
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&

              # Instalar dependencias necesarias
              pip install -r requirements.txt &&

              # Detener cualquier proceso que esté usando el puerto 5000
              sudo fuser -k 5000/tcp &&

              # Ejecutar la aplicación Flask
              gunicorn -b 0.0.0.0:5000 programa:app --daemon
          EOF
